#include "main.h"
/**
 * _atoi - a C program that convert a string to an integer.
 * @s: The string to be converted
 * Return: The number generated by converting the string
 **/
int _atoi(char *s)
{
	int i = 0, j = 0, min = 1;
	unsigned int n = 0;

	while (s[i])
	{
		if (s[i] == 45)
			min *= -1;
		while (s[i] >= 48 && s[i] <= 57)
		{
			j = 1;
			n = (n * 10) + (s[i] - '0');
			i++;
		}
		if (j == 1)
			break;
		i++;
	}
	n *= min;

	return (n);
}
